name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
      message:
        description: "Provide a message explaining this deploy"
        required: true
        type: string
      PYTHON_VERSION:
        description: "Deploy with this Python version"
        required: true
        type: string
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      PYTHON_VERSION:
        required: true
        type: string

env:
  AWS_DEFAULT_REGION: us-west-2

defaults:
  run:
    shell: bash

# See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#updating-your-github-actions-workflow
permissions:
  id-token: write # required for requesting the JWT
  contents: read # required for actions/checkout

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "${{ inputs.PYTHON_VERSION }}"

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install deploy requirements
        run: |
          uv sync --group deploy
          npm install -g aws-cdk@v2.*
          cdk --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME_ARN }}
          role-session-name: ${{ github.actor }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Convert secrets and vars to environment variables
        shell: python
        run: |
          import os

          secrets_and_vars = {
              **${{ toJson(secrets) }},
              **${{ toJson(vars) }},
          }

          with open(os.environ["GITHUB_ENV"], "a") as env_file:
              for name, value in secrets_and_vars.items():
                  # If the value contains a newline, use the delimiter syntax
                  # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#multiline-strings
                  if "\n" in value:
                      print(f"{name}<<EOF\n{value}\nEOF", file=env_file)
                  else:
                      # Standard format for single lines
                      print(f"{name}={value}", file=env_file)

      - name: Deploy to ${{ inputs.environment }}
        run: uv run cdk deploy --require-approval never
