name: HLS-VI Historical Orchestration

on:
  workflow_dispatch:
  release:
    types:
      - published
  push:
    branches:
      - main
    tags-ignore:
      - "*"
    paths:
      - ".github/workflows/*"
      - "lambdas/**/*"
      - "stack/**/*"
      - "tests/**/*"
      - "cdk.json"
      - "pyproject.toml"
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/*"
      - "lambdas/**/*"
      - "stack/**/*"
      - "tests/**/*"
      - "cdk.json"
      - "pyproject.toml"

defaults:
  run:
    shell: bash

jobs:
  config:
    # This is a hack to work around the lack of support for two other possibilities for
    # avoiding duplication of configuration values:
    #
    # (1) YAML anchors (https://yaml.org/spec/1.1/current.html#id899912) and aliases
    #     (https://yaml.org/spec/1.1/current.html#id902561)
    # (2) Availability of `env` context within `jobs.<job-id>.with.<with-id>` (see
    #     https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability)
    #
    # Alternative hack: https://github.com/actions/runner/issues/1182#issuecomment-1262870831
    runs-on: ubuntu-latest
    outputs:
      PYTHON_VERSION: "3.12"
    steps:
      - name: Configure shared values
        # Nothing to do, but at least one step is required
        run: "echo configuring environment"

  unit-tests:
    runs-on: ubuntu-latest
    needs: config
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "${{ needs.config.outputs.PYTHON_VERSION }}"

      - name: Install test requirements
        run: uv sync --all-groups

      - name: Run tests
        run: scripts/test

      - name: Check for lint
        run: scripts/lint

      - name: Run static type checking
        run: scripts/typecheck

      - name: Check uv lockfile
        run: uv lock --check

  # TODO: integration tests https://github.com/NASA-IMPACT/hls_development/issues/344

  deploy-dev:
    # Deploy to dev only on push (including merged PR) to `main` branch
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    needs:
      - config
      - unit-tests
      # - integration-tests
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      PYTHON_VERSION: "${{ needs.config.outputs.PYTHON_VERSION }}"
    secrets: inherit

  deploy-prod:
    # Deploy to Prod only on publishing a release (tag) on `main` branch
    if: github.event_name == 'release' && github.event.action == 'published'
    needs:
      - config
      - unit-tests
      # - integration-tests
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      PYTHON_VERSION: "${{ needs.config.outputs.PYTHON_VERSION }}"
    secrets: inherit
