name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12

      - name: Install package
        run: uv sync --all-groups

      - name: Run tests
        run: ./scripts/test

      - name: Check for lint
        run: ./scripts/lint

      - name: Run static type checking
        run: ./scripts/typecheck
